spring:
  profiles:
    active: default
logging:
  level:
    org.kontza: DEBUG
atmospi:
  settings:
    db: N/A
    t_unit: C
    precision: 2
    range_seconds: 604800
---
spring:
  profiles:
    default
  datasource:
    url: jdbc:postgresql://localhost:5432/atmospi
    username: atmospi
    password: atmospi
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org: error
  pattern:
    console: "%-5level %logger : %msg%n"
---
spring:
  profiles:
    dev
  jpa:
    show_sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=false
    # schema: classpath:/schema.sql
logging:
  level:
    org: info
  pattern:
    console: "%d %-5level %logger : %msg%n"
